# Generated by Django 4.2.4 on 2023-09-01 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondaryClip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clip', models.FileField(upload_to='secondary_clips/')),
            ],
        ),
    ]
