# Generated by Django 4.2.4 on 2023-09-02 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator_app', '0002_secondaryclip'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondaryclip',
            name='name',
            field=models.CharField(default='clip', max_length=100),
        ),
    ]
