# Generated by Django 4.2.5 on 2023-09-09 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator_app', '0003_secondaryclip_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoClip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('clip_file', models.FileField(upload_to='clips/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
